### ISSUE TITLE
Cura Import error

### ISSUE THREAD

**Issue by kishan8910** [jonnor/CuraServer#2]
I have installed all the requirements and installed cura on my system. I am using Ubuntu OS.
No module named Cura is the message showing.

> 127.0.0.1 - - [2018-03-26 23:19:08] "GET /favicon.ico HTTP/1.1" 404 866 0.005410
Traceback (most recent call last):
  File "/home/kishan/.local/lib/python2.7/site-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/home/kishan/.local/lib/python2.7/site-packages/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/home/kishan/dev/cura_slicer/CuraServer-master/curaserver/server.py", line 125, in slice
    ret = slicer.slice(stlpath)
  File "/home/kishan/dev/cura_slicer/CuraServer-master/curaserver/server.py", line 51, in slice
    r = self._slice(stl)
  File "/home/kishan/dev/cura_slicer/CuraServer-master/curaserver/server.py", line 58, in _slice
    import Cura
  File "/home/kishan/.local/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
ImportError: No module named Cura
127.0.0.1 - - [2018-03-26 23:19:13] "POST /slice HTTP/1.1" 500 882 0.307342

The above snippet shows the error log in my terminal.

**Comment by jonnor** [comment]
You need to find out where your Cura Python module is installed, and why it is not on the Python module path.

**Comment by city8208** [comment]
Hi,I also have the same problem on Ubuntu 18.
But I already install CURA

> sudo add-apt-repository ppa:thopiekar/cura
> sudo apt-get update
> sudo apt-get install cura

and this module still say "ImportError: No module named Cura"

**Comment by city8208** [comment]
> 我已經安裝了所有要求並在我的系統上安裝了cura。我正在使用Ubuntu OS。
> 沒有名為Cura的模塊顯示消息。
> 
> > 127.0.0.1  -   -  [2018-03-26 23:19:08]“GET /favicon.ico HTTP / 1.1”404 866 0.005410 
> > 回溯（最近一次調用最後一次）：
> > 文件“/home/kishan/.local/lib/ python2.7 / site-packages / bottle.py“，第862行，在_handle 
> > 返回route.call（** args）
> > 文件”/home/kishan/.local/lib/python2.7/site-packages/bottle.py “，第1740行，在包裝器中
> > rv =回調（* a，** ka）
> > 文件”/home/kishan/dev/cura_slicer/CuraServer-master/curaserver/server.py“，第125行，在slice 
> > ret = slicer.slice中（stlpath）
> > 文件“/home/kishan/dev/cura_slicer/CuraServer-master/curaserver/server.py”，第51行，在片段
> > r = self._slice（stl）
> > 文件“/ home / kishan / dev / cura_slicer / CuraServer -master / curaserver / server.py“，第58行，在_slice中
> > 導入Cura
> > 文件“/home/kishan/.local/lib/python2.7/site-packages/gevent/builtins.py”，第93行，**導入** 
> > 結果= _import（* args，** kwargs）
> > ImportError：沒有名為Cura 
> > 127.0的模塊.0.1  -   -  [2018-03-26 23:19:13]“POST / slice HTTP / 1.1”500 882 0.307342
> 
> 以上代碼段顯示了終端中的錯誤日誌。

Hi,You need to go  ./curaserver/server.py  and found here 
>     cura_pydir = "/usr/share/cura" # FIXME: make cross-platform

and go /usr/share/  to do this function.

>cd /usr/share/
>
>git clone https://code.alephobjects.com/diffusion/CURA/cura.git
>
>sudo apt-get install python-opengl python-numpy python-serial python-setuptools python-wxgtk3.0 
 curl python-power
>
>sudo apt-get install gcc-multilib g ++  -  multilib
>
>cd cura
>
>./package.sh debian_amd64       
>
>sudo dpkg -i ./scripts/linux/cura*.deb

and it work.
